### ISSUE TITLE
[BUG] 1st argument: not an already existing atom

### ISSUE THREAD

**Issue by bitboxer** [aesmail/kaffy#250]
**Versions Used**
Kaffy: 0.9.2
Phoenix: 1.6.15
Elixir: 1.14.1

**What's actually happening?**

I just added kaffy to a small project of mine. When I start everything, it works fine,but when I stop the app and start it again with `mix phx.server` a reload of the page crashes with:

```
Request: GET /admin/engagements/engagement/571e450d-7a85-40d2-aafe-b22d90a8d4b4
** (exit) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

        :erlang.binary_to_existing_atom("engagements", :utf8)
        (kaffy 0.9.4) lib/kaffy/utils.ex:365: Kaffy.Utils.convert_to_atom/1
        (kaffy 0.9.4) lib/kaffy/utils.ex:361: Kaffy.Utils.convert_to_atoms/2
        (kaffy 0.9.4) lib/kaffy/utils.ex:218: Kaffy.Utils.get_resource/3
        (kaffy 0.9.4) lib/kaffy_web/controllers/resource_controller.ex:92: KaffyWeb.ResourceController.show/2
        (kaffy 0.9.4) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.action/2
        (kaffy 0.9.4) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.phoenix_controller_pipeline/2
        (phoenix 1.6.15) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
```

**What should happen instead?**

Not crash when reloading page after server was restarted

**Comment by aesmail** [comment]
Does this still happen with Kaffy 0.9.4?

**Comment by lsxliron** [comment]
Yes. Below a stacktrace from 0.9.4

```
ArgumentError: errors were found at the given arguments:

  * 1st argument: not an already existing atom

  Module "erlang", in :erlang.binary_to_existing_atom/2
  File "lib/kaffy/utils.ex", line 365, in Kaffy.Utils.convert_to_atom/1
  File "lib/kaffy/utils.ex", line 361, in Kaffy.Utils.convert_to_atoms/2
  File "lib/kaffy/utils.ex", line 218, in Kaffy.Utils.get_resource/3
  File "lib/kaffy_web/controllers/resource_controller.ex", line 55, in KaffyWeb.ResourceController.index/2
  File "lib/kaffy_web/controllers/resource_controller.ex", line 1, in KaffyWeb.ResourceController.action/2
  File "lib/kaffy_web/controllers/resource_controller.ex", line 1, in KaffyWeb.ResourceController.phoenix_controller_pipeline/2
  File "lib/phoenix/router.ex", line 354, in Phoenix.Router.__call__/2
```

**Comment by bitboxer** [comment]
Yes, can confirm. This also happens in 0.9.4

**Comment by elliotb** [comment]
We also encounter this in production. It appears that if a server has had the Kaffy homepage/initial dashboard requested, all subsequent requests to that server will serve correctly. For servers that have not yet had the initial dashboard requested, but where a direct link to e.g. a resource index is used by a user (from elsewhere), they'll encounter this error.

In practice running across multiple hosts, this means that a user could load the dashboard successfully, click to visit a resource (which then is routed to a different host) and encounter this issue.

**Comment by aesmail** [comment]
I'll make sure this is fixed with the next release v0.9.5

Figured what the problem is so the fix just needs to be nicely implemented.

**Comment by jcelliott** [comment]
I'm also running into this issue. @aesmail can you point out what the problem is? Someone else might be able to implement a fix.

**Comment by nathany-copia** [comment]
Thanks @aesmail. 

I saw some "to existing atom" changes on the 0.9.5 branch, but I was still seeing errors when restarting the server and then visiting a deep link without first going to the dashboard. So I assume you're not quite done yet.

**Comment by aesmail** [comment]
@ghenry #261 might fix the issue, but I'm worried about the use of `String.to_atom/1`. This might crash the app during runtime due to dynamically creating atoms. It might not be a big deal, but you never know. I could be a bad guy and try to hit random non-existent URLs just to crash the app.

**Comment by ghenry** [comment]
For example, what do projects like https://github.com/plausible/analytics do or other projects we could look at? I'm sure it's a solved problem already?
